# Generated by .github/workflows/update-formula.yml — edit that, not this.
class Pomo < Formula
  desc "Habit tracker for the terminal, driven by a pixel-art pomodoro timer"
  homepage "https://github.com/muhalifalgibran/pixel-pomodoro"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/muhalifalgibran/pixel-pomodoro/releases/download/v0.3.0/pomo_v0.3.0_darwin_arm64.tar.gz"
      sha256 "0a59aa1607a574ef64b5d3fc9e5ec1a59ac8996b45371b93b2b4777d24791ff0"
    end
    on_intel do
      url "https://github.com/muhalifalgibran/pixel-pomodoro/releases/download/v0.3.0/pomo_v0.3.0_darwin_amd64.tar.gz"
      sha256 "b79e26cad6d1a27178cdf62b757deff45f968d7d1393155ec333a7b51284d953"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/muhalifalgibran/pixel-pomodoro/releases/download/v0.3.0/pomo_v0.3.0_linux_arm64.tar.gz"
      sha256 "bbcb96c83c6512e12f8f31e3ae914b15ce8ecfdc8b0688112ea3939ed245663c"
    end
    on_intel do
      url "https://github.com/muhalifalgibran/pixel-pomodoro/releases/download/v0.3.0/pomo_v0.3.0_linux_amd64.tar.gz"
      sha256 "b16dc292600a7786df59b6fe3b6487f5a1b1de867b93f702a2b97b5d51b090fb"
    end
  end

  def install
    bin.install "pomo"
  end

  test do
    assert_match "pomo v#{version}", shell_output("#{bin}/pomo -version")
  end
end
