# Generated by .github/workflows/update-formula.yml — edit that, not this.
class Pomo < Formula
  desc "Habit tracker for the terminal, driven by a pixel-art pomodoro timer"
  homepage "https://github.com/muhalifalgibran/pixel-pomodoro"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/muhalifalgibran/pixel-pomodoro/releases/download/v0.2.4/pomo_v0.2.4_darwin_arm64.tar.gz"
      sha256 "1ae2db56e8b066973261af8ec66d0487d811c3217f5ec6effb7474be883fcd2d"
    end
    on_intel do
      url "https://github.com/muhalifalgibran/pixel-pomodoro/releases/download/v0.2.4/pomo_v0.2.4_darwin_amd64.tar.gz"
      sha256 "56c6a6b3024548718a0e44ecfbbe4878d213003fb16c8087ac59647ce555401d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/muhalifalgibran/pixel-pomodoro/releases/download/v0.2.4/pomo_v0.2.4_linux_arm64.tar.gz"
      sha256 "e3a19321d55d36968130875243dd9a0b5b1bbaa8fd554b26236fdd187f5f4e9a"
    end
    on_intel do
      url "https://github.com/muhalifalgibran/pixel-pomodoro/releases/download/v0.2.4/pomo_v0.2.4_linux_amd64.tar.gz"
      sha256 "8f5a9954d26505272650c30db0920b41755ebbff915d66b728e7828284520da4"
    end
  end

  def install
    bin.install "pomo"
  end

  test do
    assert_match "pomo v#{version}", shell_output("#{bin}/pomo -version")
  end
end
